dashboard/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.custom_login, name='login'),  
    path('logout/', views.custom_logout, name='logout'),

    path('addFaq/', views.addFaq, name='addFaq'),
    path('updateFaq/<int:pk>/', views.updateFaq, name='updateFaq'),
    path('deleteFaq/<int:pk>/', views.deleteFaq, name='deleteFaq'),

    path('addTestimonial/', views.addTestimonial, name='addTestimonial'),
    path('editTestimonial/<int:pk>/', views.updateTestimonial, name='editTestimonial'),
    path('deleteTestimonial/<int:pk>/', views.deleteTestimonial, name='deleteTestimonial'),

    path('addPhoto/', views.addPhoto, name='photo'),
    path('addSkill/', views.addSkill, name='addSkill'),
]

hollixplicits/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls', namespace='portfolio')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views
from .views import contact_form

app_name = 'portfolio'

urlpatterns = [
    path('', views.home, name='home'),
    path('gallery/', views.gallery, name='gallery'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('contact/submit/', contact_form, name='contact_form'),
    path('services/', views.services, name='services')
]

templates/footer.html
{% load static %}
<footer id="footer" class="footer">

    <div class="container">
      <div class="copyright text-center ">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">HolliXplicits</strong> <span>All Rights Reserved</span></p>
      </div>
      <div class="social-links d-flex justify-content-center">
        <a href="https://x.com/MessachHolli"><i class="bi bi-twitter-x"></i></a>
        <a href="https://www.facebook.com/messach.holli"><i class="bi bi-facebook"></i></a>
        <a href="https://www.instagram.com/holli_xplicit_shots/"><i class="bi bi-instagram"></i></a>
        <a href="https://www.linkedin.com/in/holli-explicit-shots"><i class="bi bi-linkedin"></i></a>
      </div>
    </div>

  </footer>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <title>Holli Xplicits - Take a perfect shoot</title>
        <meta name="description" content="">
        <meta name="keywords" content="">

        <!-- Favicons -->
        <link href="{% static 'images/favicon.svg' %}" rel="icon">
        <link href="{% static 'images/apple-touch-icon.png' %}" rel="apple-touch-icon">

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com" rel="preconnect">
        <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Noto+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Questrial:wght@400&display=swap" rel="stylesheet">

        <!-- Vendor CSS Files -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

        <!-- Main CSS File -->
        <link href="{% static 'css/main.css' %}" rel="stylesheet">
        <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

        <body>
    

            {% include 'navbar.html' %}

            {% block content %} 

            {% endblock %}

            {% include 'footer.html' %}

            <!-- Scroll Top -->
            <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

            <!-- Vendor JS Files -->
            <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
            <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
            <script src="{% static 'vendor/aos/aos.js' %}"></script>
            <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
            <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
            <script src="{% static 'vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
            <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
            <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
            
            <!-- main js file -->
            <script src="{% static 'js/main.js' %}"></script>
            <script src="{% static 'js/portfolio-filter.js' %}"></script>
            <script src="{% static 'js/check-photo.js' %}"></script>
            <script src="{% static 'js/contact-form.js' %}"></script>
        </body>
</head>
</html>

templates/navbar.html
{% load static %}

<header id="header" class="header d-flex align-items-center sticky-top">
    <div class="header-container container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="{% url 'portfolio:home' %}" class="logo d-flex align-items-center me-auto me-xl-0">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <img src="{% static 'images/logo1.svg' %}">
        <h1 class="sitename">HOLLIXPLICITS</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'portfolio:home' %}" class="active">Home</a></li>
          <li><a href="{% url 'portfolio:about' %}">About</a></li>
          <li><a href="{% url 'portfolio:gallery' %}">Gallery</a></li>
          <li><a href="{% url 'portfolio:services' %}">Services</a></li>
          <li><a href="{% url 'portfolio:contact' %}">Contact</a></li>
          <li><a href="{% url 'dashboard:dashboard' %}">Dashboard</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

      <div class="header-social-links">
        <a href="https://x.com/MessachHolli"><i class="bi bi-twitter-x"></i></a>
        <a href="https://www.facebook.com/messach.holli" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="https://www.instagram.com/holli_xplicit_shots/" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="https://www.linkedin.com/in/holli-explicit-shots" class="linkedin"><i class="bi bi-linkedin"></i></a>
      </div>

    </div>
  </header>